/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ocenka;
import Entities.Ocenka;
//import Ocenka.OcenkaModel;
import Entities.Facultet;
import Entities.Student;
import Entities.Prepodavatel_Discipline;
import Entities.Prepod_and_Disc;
import Prepod_and_Disc.Prepod_and_DiscModel;
import Prepodavatel_Discipline.Prepodavatel_DisciplineModel;
import Student.StudentModel;
import Help.JTextFieldLimit;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
/**
 *
 * @author user
 */
public class NewOcenka extends javax.swing.JDialog {
   Connection c;
    Ocenka editItem;
    List<Student> list1;
   List<Prepod_and_Disc> list2;


    /**
     * Creates new form NewOcenka
     */
    
    public NewOcenka(java.awt.Frame parent, boolean modal, Connection c) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;

        ((AbstractDocument) data.getDocument()).setDocumentFilter(new JTextFieldLimit(30));//название полей в форме
        ((AbstractDocument) mark.getDocument()).setDocumentFilter(new JTextFieldLimit(30));

        
        list1 = new ArrayList<>();
        sid.setModel(new DefaultComboBoxModel(StudentModel.selectStudent(c).toArray()));
        
        list2= new ArrayList<>();
        pdid.setModel(new DefaultComboBoxModel(Prepod_and_DiscModel.selectPrepod_and_Disc(c).toArray()));
 
    }
public NewOcenka(java.awt.Frame parent, boolean modal, Connection c, Ocenka u) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;
        editItem = u;

((AbstractDocument) data.getDocument()).setDocumentFilter(new JTextFieldLimit(30));//название полей в форме
        ((AbstractDocument) mark.getDocument()).setDocumentFilter(new JTextFieldLimit(30));

       list1 = new ArrayList<>();
        sid.setModel(new DefaultComboBoxModel(StudentModel.selectStudent(c).toArray()));
        
        list2= new ArrayList<>();
        pdid.setModel(new DefaultComboBoxModel(Prepod_and_DiscModel.selectPrepod_and_Disc(c).toArray()));
     
        fillFields();
    }

private void fillFields() {//заполнение в форме нзавание полей в форме
        mark.setText(editItem.getName());
        data.setText(editItem.getData());
        
         for (Student s : list1) {
            if (s.getId() == editItem.getStudentId()) {
                sid.setSelectedItem((s));
            }
         }
            
             for (Prepod_and_Disc s : list2) {
            if (s.getId() == editItem.getPrepodavatel_DiscipleId()) {
                pdid.setSelectedItem((s));
            }
        }
       
    }

public boolean check() {
        if ("".equals(mark.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "mark cannot be empty");
            return false;
        }
            
            if ("".equals(data.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "data cannot be empty");
            return false;
            }
     
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOk1 = new javax.swing.JButton();
        sid = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mark = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pdid = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonOk1.setText("OK");
        jButtonOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOk1ActionPerformed(evt);
            }
        });

        sid.setToolTipText("");
        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });

        jLabel7.setText("Дата");

        data.setToolTipText("");
        data.setName(""); // NOI18N

        jLabel5.setText("Преподаватель и дисциплина");

        jLabel4.setText("Студент");

        mark.setToolTipText("");
        mark.setName(""); // NOI18N

        jLabel3.setText("Оценка");

        pdid.setToolTipText("");
        pdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mark)
                                    .addComponent(sid, 0, 125, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(pdid, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButtonOk1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButtonOk1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOk1ActionPerformed
//      if (!check()) {
//            return;
//      }
         try{
            OcenkaModel wm = new OcenkaModel(c);
            wm.insertOrUpdate(editItem, mark.getText(),
                ((Student) sid.getSelectedItem()).getId(),
                ((Prepod_and_Disc) pdid.getSelectedItem()).getId(),
                data.getText());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());
            return;
        }
        dispose();
    }//GEN-LAST:event_jButtonOk1ActionPerformed

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

    private void pdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdidActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField data;
    private javax.swing.JButton jButtonOk1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mark;
    private javax.swing.JComboBox<String> pdid;
    private javax.swing.JComboBox<String> sid;
    // End of variables declaration//GEN-END:variables
}
