/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;
import Entities.Student;
import Entities.Facultet;
import Entities.Gruppa;
import Gruppa.GruppaModel;
//import Student.StudentModel;
import Help.JTextFieldLimit;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
/**
 *
 * @author user
 */
public class NewStudent extends javax.swing.JDialog {

     Connection c;
    Student editItem;
    List<Gruppa> list;
    /**
     * Creates new form NewStudent
     */
     public NewStudent(java.awt.Frame parent, boolean modal, Connection c) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;

        ((AbstractDocument) surname.getDocument()).setDocumentFilter(new JTextFieldLimit(30));//название полей в форме
//        ((AbstractDocument) name.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
//        ((AbstractDocument) patronymic.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
        ((AbstractDocument) telephone.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
        ((AbstractDocument) adress.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
        ((AbstractDocument) phone.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
        list = new ArrayList<>();
        gid.setModel(new DefaultComboBoxModel(GruppaModel.selectGruppa(c).toArray()));
       
    }
     
     public NewStudent(java.awt.Frame parent, boolean modal, Connection c, Student u) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;
        editItem = u;

        ((AbstractDocument) surname.getDocument()).setDocumentFilter(new JTextFieldLimit(30));//название полей в форме
//        ((AbstractDocument) name.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
//        ((AbstractDocument) patronymic.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
        ((AbstractDocument) telephone.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
        ((AbstractDocument) adress.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
        ((AbstractDocument) phone.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
        list = new ArrayList<>();
        gid.setModel(new DefaultComboBoxModel(GruppaModel.selectGruppa(c).toArray()));
     
        fillFields();
    }
     
      private void fillFields() {//заполнение в форме нзавание полей в форме
        surname.setText(editItem.getSurname());
//        name.setText(editItem.getName());
//        patronymic.setText(editItem.getPatronymic());
        telephone.setText(editItem.getTelephone());
        adress.setText(editItem.getAdress());
        phone.setText(editItem.getTelephone_of_parents());
         for (Gruppa s : list) {
            if (s.getId() == editItem.getGruppaId()) {
                gid.setSelectedItem((s));
            }
        }
       
    }
      
      public boolean check() {
        
            if ("".equals(surname.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "surname cannot be empty");
            return false;
            }
            
       
//            if ("".equals(name.getText())) {
//            JOptionPane.showMessageDialog(new JFrame(), "name cannot be empty");
//            return false;
//            }
//            
//       
//            if ("".equals(patronymic.getText())) {
//            JOptionPane.showMessageDialog(new JFrame(), "patronymic cannot be empty");
//            return false;
//            }
        
            if ("".equals(telephone.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "telephone cannot be empty");
            return false;
            }
        
            if ("".equals(adress.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "adress cannot be empty");
            return false;
            }
            
            if ("".equals(phone.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "parent's phone cannot be empty");
        
            return false;
        }
        
        
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOk1 = new javax.swing.JButton();
        gid = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        adress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonOk1.setText("OK");
        jButtonOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOk1ActionPerformed(evt);
            }
        });

        gid.setToolTipText("");
        gid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gidActionPerformed(evt);
            }
        });

        jLabel6.setText("Группа");

        adress.setToolTipText("");
        adress.setName(""); // NOI18N

        jLabel8.setText("Адрес");

        jLabel7.setText("Телефон");

        telephone.setToolTipText("");
        telephone.setName(""); // NOI18N

        surname.setToolTipText("");
        surname.setName(""); // NOI18N

        jLabel3.setText("Фамилия");

        jLabel9.setText("Телефон родителей");

        phone.setToolTipText("");
        phone.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(telephone)
                                        .addComponent(adress))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phone)
                                    .addComponent(gid, 0, 163, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButtonOk1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonOk1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOk1ActionPerformed

        if (!check()) {
            return;
        }
        try{
            StudentModel wm = new StudentModel(c);
            wm.insertOrUpdate(editItem, surname.getText(),
                   telephone.getText(),adress.getText(),phone.getText(),
                ((Gruppa) gid.getSelectedItem()).getId());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());
            return;
        }
        dispose();
    }//GEN-LAST:event_jButtonOk1ActionPerformed

    private void gidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gidActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adress;
    private javax.swing.JComboBox<String> gid;
    private javax.swing.JButton jButtonOk1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
