/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mark;
import Entities.Mark;
//import Ocenka.OcenkaModel;
import Entities.Faculty;
import Entities.Student;
import Entities.Teacher_Discipline;
import Entities.Teacher_Discipline_View;
import Teacher_Discipline_View.Teacher_Discipline_ViewModel;
import Teacher_Discipline.Teacher_DisciplineModel;
import Student.StudentModel;
import Help.JTextFieldLimit;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
/**
 *
 * @author user
 */
public class NewMark extends javax.swing.JDialog {
   Connection c;
    Mark editItem;
    List<Student> list1;
   List<Teacher_Discipline_View> list2;


    /**
     * Creates new form NewOcenka
     */
    
    public NewMark(java.awt.Frame parent, boolean modal, Connection c) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;

        ((AbstractDocument) data.getDocument()).setDocumentFilter(new JTextFieldLimit(30));//название полей в форме
        ((AbstractDocument) mark.getDocument()).setDocumentFilter(new JTextFieldLimit(30));

        
        list1 = new ArrayList<>();
        student.setModel(new DefaultComboBoxModel(StudentModel.selectStudent(c).toArray()));
        
        list2= new ArrayList<>();
        teacher_discipline.setModel(new DefaultComboBoxModel(Teacher_Discipline_ViewModel.selectTeacher_Discipline_View(c).toArray()));
 
    }
public NewMark(java.awt.Frame parent, boolean modal, Connection c, Mark u) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;
        editItem = u;
((AbstractDocument) mark.getDocument()).setDocumentFilter(new JTextFieldLimit(30));
((AbstractDocument) data.getDocument()).setDocumentFilter(new JTextFieldLimit(30));//название полей в форме
        

       list1 = new ArrayList<>();
        student.setModel(new DefaultComboBoxModel(StudentModel.selectStudent(c).toArray()));
        
        list2= new ArrayList<>();
        teacher_discipline.setModel(new DefaultComboBoxModel(Teacher_Discipline_ViewModel.selectTeacher_Discipline_View(c).toArray()));
     
        fillFields();
    }

private void fillFields() {//заполнение в форме нзавание полей в форме
        mark.setText(editItem.getMark());
        data.setText(editItem.getData());
        
         for (Student s : list1) {
            if (s.getId() == editItem.getStudent_id()) {
                student.setSelectedItem((s));
            }
         }
            
             for (Teacher_Discipline_View s : list2) {
            if (s.getId() == editItem.getTeacher_Discipline_id()) {
                teacher_discipline.setSelectedItem((s));
            }
        }
       
    }

public boolean check() {
        if ("".equals(mark.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Введите оценку.");
            return false;
        }
            
            if ("".equals(data.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Введите дату.");
            return false;
            }
     
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOk1 = new javax.swing.JButton();
        student = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mark = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        teacher_discipline = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonOk1.setText("OK");
        jButtonOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOk1ActionPerformed(evt);
            }
        });

        student.setToolTipText("");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });

        jLabel7.setText("Дата");

        data.setToolTipText("");
        data.setName(""); // NOI18N

        jLabel5.setText("Преподаватель и дисциплина");

        jLabel4.setText("Студент");

        mark.setToolTipText("");
        mark.setName(""); // NOI18N

        jLabel3.setText("Оценка");

        teacher_discipline.setToolTipText("");
        teacher_discipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_disciplineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mark)
                            .addComponent(student, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButtonOk1)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teacher_discipline, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_discipline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addComponent(jButtonOk1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOk1ActionPerformed
//      if (!check()) {
//            return;
//      }
         try{
            MarkModel wm = new MarkModel(c);
            wm.insertOrUpdate(editItem, data.getText(),
                ((Student) student.getSelectedItem()).getId(),
                ((Teacher_Discipline_View) teacher_discipline.getSelectedItem()).getId(),mark.getText()
               );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());
            return;
        }
        dispose();
    }//GEN-LAST:event_jButtonOk1ActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentActionPerformed

    private void teacher_disciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_disciplineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_disciplineActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField data;
    private javax.swing.JButton jButtonOk1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mark;
    private javax.swing.JComboBox<String> student;
    private javax.swing.JComboBox<String> teacher_discipline;
    // End of variables declaration//GEN-END:variables
}
