/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher_Discipline;
import Entities.Teacher;
import Entities.Discipline;
import Entities.Teacher_Discipline;
import Teacher.TeacherModel;
import Discipline.DisciplineModel;
import Help.JTextFieldLimit;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
/**
 *
 * @author user
 */
public class NewTeacher_Discipline extends javax.swing.JDialog {

    /**
     * Creates new form NewTeacher_Discipline
     */
    Connection c;
    Teacher_Discipline editItem;
    List<Teacher> list1;
    List<Discipline> list2;
    
    
    public NewTeacher_Discipline(java.awt.Frame parent, boolean modal, Connection c) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;

       
        list1 = new ArrayList<>();
        teacher_name.setModel(new DefaultComboBoxModel(TeacherModel.selectTeacher(c).toArray()));
        
        list2 = new ArrayList<>();
        discipline_name.setModel(new DefaultComboBoxModel(DisciplineModel.selectDiscipline(c).toArray()));
       
    }

     public NewTeacher_Discipline(java.awt.Frame parent, boolean modal, Connection c, Teacher_Discipline u) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;
        editItem = u;

        
        list1 = new ArrayList<>();
        teacher_name.setModel(new DefaultComboBoxModel(TeacherModel.selectTeacher(c).toArray()));
     
        list2 = new ArrayList<>();
        discipline_name.setModel(new DefaultComboBoxModel(DisciplineModel.selectDiscipline(c).toArray()));
        fillFields();
    }
     
     private void fillFields() {
       
        for (Teacher s : list1) {
            if (s.getId() == editItem.getTeacher_id()) {
                teacher_name.setSelectedItem((s));
            }
        }
        for (Discipline s : list2) {
            if (s.getId() == editItem.getDiscipline_id()) {
                discipline_name.setSelectedItem((s));
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOk1 = new javax.swing.JButton();
        discipline_name = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teacher_name = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonOk1.setText("OK");
        jButtonOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOk1ActionPerformed(evt);
            }
        });

        discipline_name.setToolTipText("");

        jLabel3.setText("Преподаватель");

        jLabel6.setText("Дисциплина");

        teacher_name.setToolTipText("");
        teacher_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_nameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teacher_name, 0, 161, Short.MAX_VALUE)
                            .addComponent(discipline_name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButtonOk1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacher_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discipline_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonOk1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOk1ActionPerformed

        
        try{
            Teacher_DisciplineModel wm = new Teacher_DisciplineModel(c);
            wm.insertOrUpdate(editItem, 
                ((Teacher) teacher_name.getSelectedItem()).getId(),
                ((Discipline) discipline_name.getSelectedItem()).getId());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());
            return;
        }
        dispose();
    }//GEN-LAST:event_jButtonOk1ActionPerformed

    private void teacher_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_nameActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> discipline_name;
    private javax.swing.JButton jButtonOk1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> teacher_name;
    // End of variables declaration//GEN-END:variables
}
