/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prepodavatel_Discipline;
import Entities.Prepodavatel;
import Entities.Discipline;
import Entities.Prepodavatel_Discipline;
import Prepodavatel.PrepodavatelModel;
import Discipline.DisciplineModel;
import Help.JTextFieldLimit;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
/**
 *
 * @author user
 */
public class NewPrepodavatel_Discipline extends javax.swing.JDialog {

    /**
     * Creates new form NewPrepodavatel_Discipline
     */
    Connection c;
    Prepodavatel_Discipline editItem;
    List<Prepodavatel> list1;
    List<Discipline> list2;
    
    
    public NewPrepodavatel_Discipline(java.awt.Frame parent, boolean modal, Connection c) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;

       
        list1 = new ArrayList<>();
        prepod_id.setModel(new DefaultComboBoxModel(PrepodavatelModel.selectPrepodavatel(c).toArray()));
        
        list2 = new ArrayList<>();
        discipline_id.setModel(new DefaultComboBoxModel(DisciplineModel.selectDiscipline(c).toArray()));
       
    }

     public NewPrepodavatel_Discipline(java.awt.Frame parent, boolean modal, Connection c, Prepodavatel_Discipline u) throws SQLException {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;
        editItem = u;

        
        list1 = new ArrayList<>();
        prepod_id.setModel(new DefaultComboBoxModel(PrepodavatelModel.selectPrepodavatel(c).toArray()));
     
        list2 = new ArrayList<>();
        discipline_id.setModel(new DefaultComboBoxModel(DisciplineModel.selectDiscipline(c).toArray()));
        fillFields();
    }
     
     private void fillFields() {
       
        for (Prepodavatel s : list1) {
            if (s.getId() == editItem.getPrepodavatelId()) {
                prepod_id.setSelectedItem((s));
            }
        }
        for (Discipline s : list2) {
            if (s.getId() == editItem.getDisciplineId()) {
                discipline_id.setSelectedItem((s));
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOk1 = new javax.swing.JButton();
        discipline_id = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prepod_id = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonOk1.setText("OK");
        jButtonOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOk1ActionPerformed(evt);
            }
        });

        discipline_id.setToolTipText("");

        jLabel3.setText("Преподаватель");

        jLabel6.setText("Дисциплина");

        prepod_id.setToolTipText("");
        prepod_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prepod_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prepod_id, 0, 161, Short.MAX_VALUE)
                            .addComponent(discipline_id, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButtonOk1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prepod_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discipline_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonOk1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOk1ActionPerformed

        
        try{
            Prepodavatel_DisciplineModel wm = new Prepodavatel_DisciplineModel(c);
            wm.insertOrUpdate(editItem, 
                ((Prepodavatel) prepod_id.getSelectedItem()).getId(),
                ((Discipline) discipline_id.getSelectedItem()).getId());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());
            return;
        }
        dispose();
    }//GEN-LAST:event_jButtonOk1ActionPerformed

    private void prepod_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prepod_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prepod_idActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> discipline_id;
    private javax.swing.JButton jButtonOk1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> prepod_id;
    // End of variables declaration//GEN-END:variables
}
